# Generated by Django 3.2.5 on 2021-07-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_buttononetext_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisecategory',
            name='is_view',
            field=models.BooleanField(default=False, verbose_name='Отображение'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_view',
            field=models.BooleanField(default=False, verbose_name='Отображение'),
        ),
    ]
