# Generated by Django 3.2.5 on 2021-07-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210713_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buttononetext',
            options={'verbose_name': 'Шаблон сообщения', 'verbose_name_plural': 'Шаблоны сообщений'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'рецепты'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категория рецептов', 'verbose_name_plural': 'Категории рецептов'},
        ),
    ]
