# Generated by Django 3.2.5 on 2021-07-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20210714_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=12)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
