# Generated by Django 3.2.5 on 2021-07-14 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст публицаии')),
                ('send_date_time', models.DateTimeField(default=datetime.datetime(2021, 7, 14, 13, 3, 31, 393171), verbose_name='Время отправки')),
                ('is_sended', models.BooleanField(default=False, verbose_name='Было отправлено')),
                ('description', models.TextField(verbose_name='Описание')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на фото')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('button_url', models.URLField(blank=True, null=True, verbose_name='Ссылка кнопки действия')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
