# Generated by Django 3.2.5 on 2021-07-14 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictribution',
            name='name',
            field=models.CharField(default='Test', max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictribution',
            name='send_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 13, 5, 16, 693515), verbose_name='Время отправки'),
        ),
    ]
