# Generated by Django 3.2.5 on 2021-07-14 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictribution', '0003_auto_20210714_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictribution',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='dictribution',
            name='video_url',
        ),
        migrations.AddField(
            model_name='dictribution',
            name='content_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фото или видео'),
        ),
        migrations.AlterField(
            model_name='dictribution',
            name='button_name',
            field=models.CharField(default='Нет кнопки', max_length=100, verbose_name='Имя кнопки'),
        ),
        migrations.AlterField(
            model_name='dictribution',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dictribution',
            name='send_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 19, 47, 14, 167301), verbose_name='Время отправки'),
        ),
    ]
